routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');


Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);

    Route::resource('states', 'Admin\StateController');
    Route::post('states_mass_destroy', ['uses' => 'Admin\StateController@massDestroy', 'as' => 'states.mass_destroy']);

    Route::resource('locations', 'Admin\LocationController');
    Route::post('loations_mass_destroy', ['uses' => 'Admin\LocationController@massDestroy', 'as' => 'locations.mass_destroy']);
});

Route::group(['middleware' => ['auth'], 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('/home', 'HomeController@dashboard');
    
});


Route::post('/state','AjaxController@state')->name('state');

//MIS Routes
Route::get('/importexcel/index','ImportExcelController@index')->name('importexcel.index');
Route::get('/importexcel/uploadmis','ImportExcelController@uploadmis')->name('importexcel.uploadmis');
Route::post('/importexcel/savemis','ImportExcelController@savemis')->name('importexcel.savemis');
Route::get('/importexcel/viewmisdata/{id}','ImportExcelController@viewmisdata')->name('importexcel.viewmisdata');
Route::get('/importexcel/editmisdata/{id}','ImportExcelController@editmisdata')->name('importexcel.editmisdata');
Route::post('/importexcel/saveupdatedmisdata/{id}','ImportExcelController@saveupdatedmisdata')->name('importexcel.saveupdatedmisdata');

Route::get('/importexcel/dtrdownload','ImportExcelController@dtrdownload')->name('importexcel.dtrdownload');
Route::get('/importexcel/cmdownload','ImportExcelController@cmdownload')->name('importexcel.cmdownload');
Route::get('/importexcel/viewallassignedwarehouses','ImportExcelController@viewallassignedwarehouses')->name('importexcel.viewallassignedwarehouses');



//Audit Inspection Routes
Route::get('/auditinspection/index','AuditInspectionController@index')->name('auditinspection.index');
Route::get('/auditinspection/add/{id}','AuditInspectionController@add')->name('auditinspection.add');
Route::get('/auditinspection/addmore/{id}','AuditInspectionController@addmore')->name('auditinspection.addmore');
Route::post('/auditinspection/save','AuditInspectionController@save')->name('auditinspection.save');
Route::post('/auditinspection/savemore/{id}','AuditInspectionController@savemore')->name('auditinspection.savemore');
Route::post('/auditinspection/edit/{id}','AuditInspectionController@edit')->name('auditinspection.edit');
Route::delete('/auditinspection/delete/{id}','AuditInspectionController@delete')->name('auditinspection.delete');
Route::get('/auditinspection/edit/{id}','AuditInspectionController@edit')->name('auditinspection.edit');
Route::put('/auditinspection/update/{id}','AuditInspectionController@update')->name('auditinspection.update');
Route::get('/auditinspection/editmore/{id}','AuditInspectionController@editmore')->name('auditinspection.editmore');
Route::put('/auditinspection/updatemore/{id}','AuditInspectionController@updatemore')->name('auditinspection.updatemore');

Route::get('/auditinspection/view/{id}','AuditInspectionController@view')->name('auditinspection.view');

Route::get('/auditinspection/list','AuditInspectionController@listing')->name('auditinspection.list');

Route::post('/auditinspection/assign','AuditInspectionController@assign')->name('auditinspection.assign');

Route::post('/auditinspection/assign','AuditInspectionController@assign')->name('auditinspection.assign');

Route::post('/auditinspection/approve','AuditInspectionController@approve')->name('auditinspection.approve');

Route::post('/auditinspection/reject','AuditInspectionController@reject')->name('auditinspection.reject');

Route::post('/auditinspection/addcomment','AuditInspectionController@addcomment')->name('auditinspection.addcomment');

Route::post('/auditinspection/check','AuditInspectionController@check')->name('auditinspection.check');

Route::get('/auditinspection/escalationfield','AuditInspectionController@escalationfield')->name('auditinspection.escalationfield');

Route::get('/auditinspection/getuser','AuditInspectionController@getuser')->name('auditinspection.getuser');

Route::post('/auditinspection/savepv','AuditInspectionController@savepv')->name('auditinspection.savepv');

Route::get('/auditinspection/uploadauditvideo/{id}','AuditInspectionController@uploadauditvideo')->name('auditinspection.uploadauditvideo');

Route::post('/auditinspection/saveauditvideo','AuditInspectionController@saveauditvideo')->name('auditinspection.saveauditvideo');

Route::get('/auditinspection/editauditvideo/{id}','AuditInspectionController@editauditvideo')->name('auditinspection.editauditvideo');

Route::put('/auditinspection/updateauditvideo/{id}','AuditInspectionController@updateauditvideo')->name('auditinspection.updateauditvideo');

Route::post('/auditinspection/clusterheads','AuditInspectionController@clusterheads')->name('auditinspection.clusterheads');


//Routes for reports
Route::group(['middleware' => ['auth'], 'prefix' => 'reports', 'as' => 'reports.'], function () {

    Route::get('plannedwarehouses', ['uses'=>'Admin\ReportController@plannedwarehouses','as' => 'plannedwarehouses']);

    Route::get('auditedwarehouses', ['uses'=>'Admin\ReportController@auditedwarehouses','as' => 'auditedwarehouses']);

    Route::get('clientwiseplannedwarehouses', ['uses'=>'Admin\ReportController@clientwiseplannedwarehouses','as' => 'clientwiseplannedwarehouses']);

    Route::get('auditfindings', ['uses'=>'Admin\ReportController@auditfindings','as' => 'auditfindings']);

    Route::get('clientwisedetail', ['uses'=>'Admin\ReportController@clientwisedetail','as' => 'clientwisedetail']);

    Route::get('auditfindingsdetail', ['uses'=>'Admin\ReportController@auditfindingsdetail','as' => 'auditfindingsdetail']);

    Route::get('auditfindingsdishonoured', ['uses'=>'Admin\ReportController@auditfindingsdishonoured','as' => 'auditfindingsdishonoured']);

    Route::get('auditfindingsdetaildishonoured', ['uses'=>'Admin\ReportController@auditfindingsdetaildishonoured','as' => 'auditfindingsdetaildishonoured']);

    Route::get('warehousewisemismatchreport', ['uses'=>'Admin\ReportController@warehousewisemismatchreport','as' => 'warehousewisemismatchreport']);

    Route::get('warehousewisemismatchreportdetail', ['uses'=>'Admin\ReportController@warehousewisemismatchreportdetail','as' => 'warehousewisemismatchreportdetail']);    
    
});

Route::get('/reminder/sendescalations','ReminderController@sendescalations')->name('auditinspection.sendescalations');


//use App\User;
Route::get("/test",function(){
	//echo "test";
	//echo route('auth.login');
	//echo url('login');
	 //abort(401);
	echo "<pre>";
	print_r(App\User::all()->toArray());
	//print_r(App\User::all()->pluck('name','name'));
	//dd(App\User::all());
})->middleware('Logger');

Route::get("/upload",function(){

    return view('upload');

})->name('upload');

Route::post("/save",function(){
    //dd(request()->file('image'));
    // $result = request()->file('image')->store(
    //     'aryapro',
    //     's3'
    // );
    $file = request()->file('image');
    //print_r($file);die;
    $imageName = 'aryapro/'.$file->getClientOriginalName();

    Storage::disk('s3')->put($imageName, file_get_contents($file));
    Storage::disk('s3')->setVisibility($imageName, 'public');

    $url = Storage::disk('s3')->url($imageName);
    //print_r($url);die;
    return back();
})->name('save');

Route::get('send','MailController@send');

Route::get("/internetnotify",function(){

    return view('internetnotify');

})->name('internetnotify');

Route::get('updateusingcsv','ImportExcelController@updateusingcsv');

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreRolesRequest;
use App\Http\Requests\Admin\UpdateRolesRequest;

class RolesController extends Controller
{
    /**
     * Display a listing of Role.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('users_manage')) {
            return abort(401);
        }

        $roles = Role::all();

        return view('admin.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating new Role.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('users_manage')) {
            return abort(401);
        }
        $permissions = Permission::get()->pluck('name', 'name');

        return view('admin.roles.create', compact('permissions'));
    }

    /**
     * Store a newly created Role in storage.
     *
     * @param  \App\Http\Requests\StoreRolesRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRolesRequest $request)
    {
        if (! Gate::allows('users_manage')) {
            return abort(401);
        }
        $role = Role::create($request->except('permission'));
        $permissions = $request->input('permission') ? $request->input('permission') : [];
        $role->givePermissionTo($permissions);

        return redirect()->route('admin.roles.index');
    }


    /**
     * Show the form for editing Role.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('users_manage')) {
            return abort(401);
        }
        $permissions = Permission::get()->pluck('name', 'name');

        $role = Role::findOrFail($id);

        return view('admin.roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update Role in storage.
     *
     * @param  \App\Http\Requests\UpdateRolesRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRolesRequest $request, $id)
    {
        if (! Gate::allows('users_manage')) {
            return abort(401);
        }
        $role = Role::findOrFail($id);
        $role->update($request->except('permission'));
        $permissions = $request->input('permission') ? $request->input('permission') : [];
        $role->syncPermissions($permissions);

        return redirect()->route('admin.roles.index');
    }


    /**
     * Remove Role from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('users_manage')) {
            return abort(401);
        }
        $role = Role::findOrFail($id);
        $role->delete();

        return redirect()->route('admin.roles.index');
    }

    /**
     * Delete all selected Role at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('users_manage')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Role::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

}

resources/views/admin/roles/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.roles.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.roles.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('name', 'Name*', ['class' => 'control-label']) !!}
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('name'))
                        <p class="help-block">
                            {{ $errors->first('name') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('permission', 'Permissions', ['class' => 'control-label']) !!}
                    {!! Form::select('permission[]', $permissions, old('permission'), ['class' => 'form-control select2', 'multiple' => 'multiple']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('permission'))
                        <p class="help-block">
                            {{ $errors->first('permission') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('global.app_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/admin/roles/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.roles.title')</h3>
    
    {!! Form::model($role, ['method' => 'PUT', 'route' => ['admin.roles.update', $role->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('name', 'Name*', ['class' => 'control-label']) !!}
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('name'))
                        <p class="help-block">
                            {{ $errors->first('name') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('permission', 'Permissions', ['class' => 'control-label']) !!}
                    {!! Form::select('permission[]', $permissions, old('permission') ? old('permission') : $role->permissions()->pluck('name', 'name'), ['class' => 'form-control select2', 'multiple' => 'multiple']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('permission'))
                        <p class="help-block">
                            {{ $errors->first('permission') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('global.app_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/admin/roles/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.roles.title')</h3>
    <p>
        <a href="{{ route('admin.roles.create') }}" class="btn btn-success">@lang('global.app_add_new')</a>
    </p>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($roles) > 0 ? 'datatable' : '' }} dt-select">
                <thead>
                    <tr>               
                        <th>@lang('global.roles.fields.name')</th>
                        <th>@lang('global.roles.fields.permission')</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                
                <tbody>
                    @if (count($roles) > 0)
                        @foreach ($roles as $role)
                            <tr>
                               
                                <td>{{ $role->name }}</td>
                                <td>
                                    @foreach ($role->permissions()->pluck('name') as $permission)
                                        <span class="label label-info label-many">{{ $permission }}</span>
                                    @endforeach
                                </td>
                                <td>
                                    <a href="{{ route('admin.roles.edit',[$role->id]) }}" class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['admin.roles.destroy', $role->id])) !!}
                                    {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="6">@lang('global.app_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        window.route_mass_crud_entries_destroy = '{{ route('admin.roles.mass_destroy') }}';
    </script>
@endsection