routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');


Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);

    Route::resource('states', 'Admin\StateController');
    Route::post('states_mass_destroy', ['uses' => 'Admin\StateController@massDestroy', 'as' => 'states.mass_destroy']);

    Route::resource('locations', 'Admin\LocationController');
    Route::post('loations_mass_destroy', ['uses' => 'Admin\LocationController@massDestroy', 'as' => 'locations.mass_destroy']);
});

Route::group(['middleware' => ['auth'], 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('/home', 'HomeController@dashboard');
    
});


Route::post('/state','AjaxController@state')->name('state');

//MIS Routes
Route::get('/importexcel/index','ImportExcelController@index')->name('importexcel.index');
Route::get('/importexcel/uploadmis','ImportExcelController@uploadmis')->name('importexcel.uploadmis');
Route::post('/importexcel/savemis','ImportExcelController@savemis')->name('importexcel.savemis');
Route::get('/importexcel/viewmisdata/{id}','ImportExcelController@viewmisdata')->name('importexcel.viewmisdata');
Route::get('/importexcel/editmisdata/{id}','ImportExcelController@editmisdata')->name('importexcel.editmisdata');
Route::post('/importexcel/saveupdatedmisdata/{id}','ImportExcelController@saveupdatedmisdata')->name('importexcel.saveupdatedmisdata');

Route::get('/importexcel/dtrdownload','ImportExcelController@dtrdownload')->name('importexcel.dtrdownload');
Route::get('/importexcel/cmdownload','ImportExcelController@cmdownload')->name('importexcel.cmdownload');
Route::get('/importexcel/viewallassignedwarehouses','ImportExcelController@viewallassignedwarehouses')->name('importexcel.viewallassignedwarehouses');



//Audit Inspection Routes
Route::get('/auditinspection/index','AuditInspectionController@index')->name('auditinspection.index');
Route::get('/auditinspection/add/{id}','AuditInspectionController@add')->name('auditinspection.add');
Route::get('/auditinspection/addmore/{id}','AuditInspectionController@addmore')->name('auditinspection.addmore');
Route::post('/auditinspection/save','AuditInspectionController@save')->name('auditinspection.save');
Route::post('/auditinspection/savemore/{id}','AuditInspectionController@savemore')->name('auditinspection.savemore');
Route::post('/auditinspection/edit/{id}','AuditInspectionController@edit')->name('auditinspection.edit');
Route::delete('/auditinspection/delete/{id}','AuditInspectionController@delete')->name('auditinspection.delete');
Route::get('/auditinspection/edit/{id}','AuditInspectionController@edit')->name('auditinspection.edit');
Route::put('/auditinspection/update/{id}','AuditInspectionController@update')->name('auditinspection.update');
Route::get('/auditinspection/editmore/{id}','AuditInspectionController@editmore')->name('auditinspection.editmore');
Route::put('/auditinspection/updatemore/{id}','AuditInspectionController@updatemore')->name('auditinspection.updatemore');

Route::get('/auditinspection/view/{id}','AuditInspectionController@view')->name('auditinspection.view');

Route::get('/auditinspection/list','AuditInspectionController@listing')->name('auditinspection.list');

Route::post('/auditinspection/assign','AuditInspectionController@assign')->name('auditinspection.assign');

Route::post('/auditinspection/assign','AuditInspectionController@assign')->name('auditinspection.assign');

Route::post('/auditinspection/approve','AuditInspectionController@approve')->name('auditinspection.approve');

Route::post('/auditinspection/reject','AuditInspectionController@reject')->name('auditinspection.reject');

Route::post('/auditinspection/addcomment','AuditInspectionController@addcomment')->name('auditinspection.addcomment');

Route::post('/auditinspection/check','AuditInspectionController@check')->name('auditinspection.check');

Route::get('/auditinspection/escalationfield','AuditInspectionController@escalationfield')->name('auditinspection.escalationfield');

Route::get('/auditinspection/getuser','AuditInspectionController@getuser')->name('auditinspection.getuser');

Route::post('/auditinspection/savepv','AuditInspectionController@savepv')->name('auditinspection.savepv');

Route::get('/auditinspection/uploadauditvideo/{id}','AuditInspectionController@uploadauditvideo')->name('auditinspection.uploadauditvideo');

Route::post('/auditinspection/saveauditvideo','AuditInspectionController@saveauditvideo')->name('auditinspection.saveauditvideo');

Route::get('/auditinspection/editauditvideo/{id}','AuditInspectionController@editauditvideo')->name('auditinspection.editauditvideo');

Route::put('/auditinspection/updateauditvideo/{id}','AuditInspectionController@updateauditvideo')->name('auditinspection.updateauditvideo');

Route::post('/auditinspection/clusterheads','AuditInspectionController@clusterheads')->name('auditinspection.clusterheads');


//Routes for reports
Route::group(['middleware' => ['auth'], 'prefix' => 'reports', 'as' => 'reports.'], function () {

    Route::get('plannedwarehouses', ['uses'=>'Admin\ReportController@plannedwarehouses','as' => 'plannedwarehouses']);

    Route::get('auditedwarehouses', ['uses'=>'Admin\ReportController@auditedwarehouses','as' => 'auditedwarehouses']);

    Route::get('clientwiseplannedwarehouses', ['uses'=>'Admin\ReportController@clientwiseplannedwarehouses','as' => 'clientwiseplannedwarehouses']);

    Route::get('auditfindings', ['uses'=>'Admin\ReportController@auditfindings','as' => 'auditfindings']);

    Route::get('clientwisedetail', ['uses'=>'Admin\ReportController@clientwisedetail','as' => 'clientwisedetail']);

    Route::get('auditfindingsdetail', ['uses'=>'Admin\ReportController@auditfindingsdetail','as' => 'auditfindingsdetail']);

    Route::get('auditfindingsdishonoured', ['uses'=>'Admin\ReportController@auditfindingsdishonoured','as' => 'auditfindingsdishonoured']);

    Route::get('auditfindingsdetaildishonoured', ['uses'=>'Admin\ReportController@auditfindingsdetaildishonoured','as' => 'auditfindingsdetaildishonoured']);

    Route::get('warehousewisemismatchreport', ['uses'=>'Admin\ReportController@warehousewisemismatchreport','as' => 'warehousewisemismatchreport']);

    Route::get('warehousewisemismatchreportdetail', ['uses'=>'Admin\ReportController@warehousewisemismatchreportdetail','as' => 'warehousewisemismatchreportdetail']);    
    
});

Route::get('/reminder/sendescalations','ReminderController@sendescalations')->name('auditinspection.sendescalations');


//use App\User;
Route::get("/test",function(){
	//echo "test";
	//echo route('auth.login');
	//echo url('login');
	 //abort(401);
	echo "<pre>";
	print_r(App\User::all()->toArray());
	//print_r(App\User::all()->pluck('name','name'));
	//dd(App\User::all());
})->middleware('Logger');

Route::get("/upload",function(){

    return view('upload');

})->name('upload');

Route::post("/save",function(){
    //dd(request()->file('image'));
    // $result = request()->file('image')->store(
    //     'aryapro',
    //     's3'
    // );
    $file = request()->file('image');
    //print_r($file);die;
    $imageName = 'aryapro/'.$file->getClientOriginalName();

    Storage::disk('s3')->put($imageName, file_get_contents($file));
    Storage::disk('s3')->setVisibility($imageName, 'public');

    $url = Storage::disk('s3')->url($imageName);
    //print_r($url);die;
    return back();
})->name('save');

Route::get('send','MailController@send');

Route::get("/internetnotify",function(){

    return view('internetnotify');

})->name('internetnotify');

Route::get('updateusingcsv','ImportExcelController@updateusingcsv');

resources/views/partials/head.blade.php
<meta charset="utf-8">
<title>
    {{ trans('global.global_title') }}
</title>

<meta http-equiv="X-UA-Compatible"
      content="IE=edge">
<meta content="width=device-width, initial-scale=1.0"
      name="viewport"/>
<meta http-equiv="Content-type"
      content="text/html; charset=utf-8">

<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<link href="{{ url('adminlte/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
<link rel="stylesheet"
      href="{{ url('adminlte/css') }}/select2.min.css"/>
<link href="{{ url('adminlte/css/AdminLTE.min.css') }}" rel="stylesheet">
<link href="{{ url('adminlte/css/skins/skin-blue.min.css') }}" rel="stylesheet">
<link rel="stylesheet"
      href="https://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
<link rel="stylesheet"
      href="//cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css"/>
<link rel="stylesheet"
      href="https://cdn.datatables.net/select/1.2.0/css/select.dataTables.min.css"/>
<link rel="stylesheet"
      href="//cdn.datatables.net/buttons/1.2.4/css/buttons.dataTables.min.css"/>
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.4.5/jquery-ui-timepicker-addon.min.css"/>
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.standalone.min.css"/>

resources/views/partials/header.blade.php
<div class="page-header-inner">
    <div class="page-header-inner">
        <div class="navbar-header">
            <a href="{{ url('/admin/home') }}"
               class="navbar-brand">
                @trans('global.global_title')
            </a>
        </div>
        <a href="javascript:;"
           class="menu-toggler responsive-toggler"
           data-toggle="collapse"
           data-target=".navbar-collapse">
        </a>

        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">

            </ul>
        </div>
    </div>
</div>

resources/views/partials/javascripts.blade.php
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="//cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
<script src="//cdn.datatables.net/buttons/1.2.4/js/dataTables.buttons.min.js"></script>
<script src="//cdn.datatables.net/buttons/1.2.4/js/buttons.flash.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.print.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.colVis.min.js"></script>
<script src="https://cdn.datatables.net/select/1.2.0/js/dataTables.select.min.js"></script>
<script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
<script src="{{ url('adminlte/js') }}/bootstrap.min.js"></script>
<script src="{{ url('adminlte/js') }}/select2.full.min.js"></script>
<script src="{{ url('adminlte/js') }}/main.js"></script>

<script src="{{ url('adminlte/plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
<script src="{{ url('adminlte/plugins/fastclick/fastclick.js') }}"></script>
<script src="{{ url('adminlte/js/app.min.js') }}"></script>
<script src="{{ url('adminlte/plugins/datepicker/bootstrap-datepicker.js') }}"></script>
<script>
    window._token = '{{ csrf_token() }}';
</script>



@yield('javascript')

resources/views/partials/sidebar.blade.php
@inject('request', 'Illuminate\Http\Request')
<!-- Left side column. contains the sidebar -->
<?php 
    $role = Auth::user()->roles->pluck('name')->first();
?>
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <ul class="sidebar-menu">

            <li class="{{ $request->segment(1) == 'home' ? 'active' : '' }}">
                <a href="{{ url('/') }}">
                    <i class="fa fa-wrench"></i>
                    <span class="title">@lang('global.app_dashboard')</span>
                </a>
            </li>
            
            @can('users_manage')
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-users"></i>
                    <span class="title">@lang('global.user-management.title')</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">

                    <li class="{{ $request->segment(2) == 'permissions' ? 'active active-sub' : '' }}">
                        <a href="{{ route('admin.permissions.index') }}">
                            <i class="fa fa-briefcase"></i>
                            <span class="title">
                                @lang('global.permissions.title')
                            </span>
                        </a>
                    </li>
                    <li class="{{ $request->segment(2) == 'roles' ? 'active active-sub' : '' }}">
                        <a href="{{ route('admin.roles.index') }}">
                            <i class="fa fa-briefcase"></i>
                            <span class="title">
                                @lang('global.roles.title')
                            </span>
                        </a>
                    </li>
                    <li class="{{ $request->segment(2) == 'users' ? 'active active-sub' : '' }}">
                        <a href="{{ route('admin.users.index') }}">
                            <i class="fa fa-user"></i>
                            <span class="title">
                                @lang('global.users.title')
                            </span>
                        </a>
                    </li>
                    
                </ul>
            </li>
            @endcan

            
            @can('states_manage')
            <li class="{{ $request->segment(2) == 'states' ? 'active active-sub' : '' }}">
                <a href="{{ route('admin.states.index') }}">
                    <i class="fa fa-user"></i>
                    <span class="title">
                        @lang('global.states.title')
                    </span>
                </a>
            </li>
            <li class="{{ $request->segment(2) == 'locations' ? 'active active-sub' : '' }}">
                <a href="{{ route('admin.locations.index') }}">
                    <i class="fa fa-user"></i>
                    <span class="title">
                        Locations
                    </span>
                </a>
            </li>
            @endcan

            @can('mis_manage')
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-user"></i>
                    <span class="title">Warehouse Assignment</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="{{ $request->segment(1) == 'importexcel' ? 'active active-sub' : '' }}">
                        <a href="{{ route('importexcel.index') }}">
                            <i class="fa fa-user"></i>
                            <span class="title">
                                Warehouse Assignment
                            </span>
                        </a>
                    </li>
                    <li class="{{ $request->segment(2) == 'viewallassignedwarehouses' ? 'active active-sub' : '' }}">
                        <a href="{{ route('importexcel.viewallassignedwarehouses') }}">
                            <i class="fa fa-bar-chart"></i>
                            <span class="title">
                                Assigned Warehouses
                            </span>
                        </a>
                    </li>
                    
                </ul>
            </li>
            @endcan
            @can('inspection_manage')
            <li class="{{ $request->segment(1) == 'auditinspection' ? 'active active-sub' : '' }}">
                <a href="{{ route('auditinspection.index') }}">
                    <i class="fa fa-user"></i>
                    <span class="title">
                        Audit Inspection
                    </span>
                </a>
            </li>
            @endcan
            @can('reports_manage')
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-file"></i>
                    <span class="title">Reports</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">

                    <!-- <li class="{{ $request->segment(2) == 'plannedwarehouses' ? 'active active-sub' : '' }}">
                        <a href="{{ route('reports.plannedwarehouses') }}">
                            <i class="fa fa-bar-chart"></i>
                            <span class="title">
                                 Planned Warehouses
                            </span>
                        </a>
                    </li>

                    <li class="{{ $request->segment(2) == 'auditedwarehouses' ? 'active active-sub' : '' }}">
                        <a href="{{ route('reports.auditedwarehouses') }}">
                            <i class="fa fa-pie-chart"></i>
                            <span class="title">
                                Warehouse Audited
                            </span>
                        </a>
                    </li> -->

                    <li class="{{ $request->segment(2) == 'clientwiseplannedwarehouses' ? 'active active-sub' : '' }}">
                        <a href="{{ route('reports.clientwiseplannedwarehouses') }}">
                            <i class="fa fa-bar-chart"></i>
                            <span class="title">
                                Clientwise Planned Warehouses
                            </span>
                        </a>
                    </li>

                    <li class="{{ $request->segment(2) == 'auditfindings' ? 'active active-sub' : '' }}">
                        <a href="{{ route('reports.auditfindings') }}">
                            <i class="fa fa-bar-chart"></i>
                            <span class="title">
                                Audit Findings
                            </span>
                        </a>
                    </li>
                    @role('administrator')
                    <li class="{{ $request->segment(2) == 'auditfindingsdishonoured' ? 'active active-sub' : '' }}">
                        <a href="{{ route('reports.auditfindingsdishonoured') }}">
                            <i class="fa fa-bar-chart"></i>
                            <span class="title">
                                Audit Findings(Dishonoured)
                            </span>
                        </a>
                    </li>

                    <li class="{{ $request->segment(2) == 'warehousewisemismatchreport' ? 'active active-sub' : '' }}">
                        <a href="{{ route('reports.warehousewisemismatchreport') }}">
                            <i class="fa fa-bar-chart"></i>
                            <span class="title">
                                Stock Mismatch
                            </span>
                        </a>
                    </li>  
                    @endrole
                </ul>
            </li>
            @endcan
            <li class="{{ $request->segment(1) == 'change_password' ? 'active' : '' }}">
                <a href="{{ route('auth.change_password') }}">
                    <i class="fa fa-key"></i>
                    <span class="title">Change password</span>
                </a>
            </li>

            <li>
                <a href="#logout" onclick="$('#logout').submit();">
                    <i class="fa fa-arrow-left"></i>
                    <span class="title">@lang('global.app_logout')</span>
                </a>
            </li>
        </ul>
    </section>
</aside>
{!! Form::open(['route' => 'auth.logout', 'style' => 'display:none;', 'id' => 'logout']) !!}
<button type="submit">@lang('global.logout')</button>
{!! Form::close() !!}


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">

    <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" style="position: absolute; top: 50px; right: 15px;z-index: 1;">
          <div class="toast-header">
              <i class="bi bi-wifi"></i>&nbsp;&nbsp;&nbsp;
              <strong class="mr-auto"><span class="text-success">Internet is Connected</span></strong>
          </div>        
      </div>
<script>

var status = 'online';
var current_status = 'online';

function check_internet_connection()
{
    if(navigator.onLine)
    {
        status = 'online';
    }
    else
    {
        status = 'offline';
    }

    if(current_status != status)
    {
        if(status == 'online')
        {
            $('i.bi').addClass('bi-wifi');
            $('i.bi').removeClass('bi-wifi-off');
            $('.mr-auto').html("<span class='text-success'>Internet is connected</span>");
        }
        else
        {
            $('i.bi').addClass('bi-wifi-off');
            $('i.bi').removeClass('bi-wifi');
            $('.mr-auto').html("<span class='text-danger'>Internet is disconnected</span>");
        }

        current_status = status;

        $('.toast').toast({
            autohide:false
        });

        $('.toast').toast('show');
    }
}

check_internet_connection();

setInterval(function(){
    check_internet_connection();
}, 1000);

</script>

resources/views/partials/topbar.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="{{ url('/admin/home') }}" class="logo"
       style="font-size: 16px;">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">
           @lang('global.global_title')</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">
           @lang('global.global_title')</span>
    </a>

    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="#" class="user-image" >
                  <span class="hidden-xs"><?= Auth::user()->name?></span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    <img src="#" class="img-circle" >
                    <p>
                      <?php $user = Auth::user();
                      echo $user->name." - ".$user->roles->pluck('name')[0];
                       ?>
                     <!--  <small>Member since Nov. 2012</small> -->
                    </p>
                  </li>
                  
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="#" class="btn btn-default btn-flat">Profile</a>
                    </div>
                    <div class="pull-right">
                      <a href="#logout" onclick="$('#logout').submit();" class="btn btn-default btn-flat">Sign out</a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>

        

    </nav>
</header>