routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');


Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);

    Route::resource('states', 'Admin\StateController');
    Route::post('states_mass_destroy', ['uses' => 'Admin\StateController@massDestroy', 'as' => 'states.mass_destroy']);

    Route::resource('locations', 'Admin\LocationController');
    Route::post('loations_mass_destroy', ['uses' => 'Admin\LocationController@massDestroy', 'as' => 'locations.mass_destroy']);
});

Route::group(['middleware' => ['auth'], 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('/home', 'HomeController@dashboard');
    
});


Route::post('/state','AjaxController@state')->name('state');

//MIS Routes
Route::get('/importexcel/index','ImportExcelController@index')->name('importexcel.index');
Route::get('/importexcel/uploadmis','ImportExcelController@uploadmis')->name('importexcel.uploadmis');
Route::post('/importexcel/savemis','ImportExcelController@savemis')->name('importexcel.savemis');
Route::get('/importexcel/viewmisdata/{id}','ImportExcelController@viewmisdata')->name('importexcel.viewmisdata');
Route::get('/importexcel/editmisdata/{id}','ImportExcelController@editmisdata')->name('importexcel.editmisdata');
Route::post('/importexcel/saveupdatedmisdata/{id}','ImportExcelController@saveupdatedmisdata')->name('importexcel.saveupdatedmisdata');

Route::get('/importexcel/dtrdownload','ImportExcelController@dtrdownload')->name('importexcel.dtrdownload');
Route::get('/importexcel/cmdownload','ImportExcelController@cmdownload')->name('importexcel.cmdownload');
Route::get('/importexcel/viewallassignedwarehouses','ImportExcelController@viewallassignedwarehouses')->name('importexcel.viewallassignedwarehouses');



//Audit Inspection Routes
Route::get('/auditinspection/index','AuditInspectionController@index')->name('auditinspection.index');
Route::get('/auditinspection/add/{id}','AuditInspectionController@add')->name('auditinspection.add');
Route::get('/auditinspection/addmore/{id}','AuditInspectionController@addmore')->name('auditinspection.addmore');
Route::post('/auditinspection/save','AuditInspectionController@save')->name('auditinspection.save');
Route::post('/auditinspection/savemore/{id}','AuditInspectionController@savemore')->name('auditinspection.savemore');
Route::post('/auditinspection/edit/{id}','AuditInspectionController@edit')->name('auditinspection.edit');
Route::delete('/auditinspection/delete/{id}','AuditInspectionController@delete')->name('auditinspection.delete');
Route::get('/auditinspection/edit/{id}','AuditInspectionController@edit')->name('auditinspection.edit');
Route::put('/auditinspection/update/{id}','AuditInspectionController@update')->name('auditinspection.update');
Route::get('/auditinspection/editmore/{id}','AuditInspectionController@editmore')->name('auditinspection.editmore');
Route::put('/auditinspection/updatemore/{id}','AuditInspectionController@updatemore')->name('auditinspection.updatemore');

Route::get('/auditinspection/view/{id}','AuditInspectionController@view')->name('auditinspection.view');

Route::get('/auditinspection/list','AuditInspectionController@listing')->name('auditinspection.list');

Route::post('/auditinspection/assign','AuditInspectionController@assign')->name('auditinspection.assign');

Route::post('/auditinspection/assign','AuditInspectionController@assign')->name('auditinspection.assign');

Route::post('/auditinspection/approve','AuditInspectionController@approve')->name('auditinspection.approve');

Route::post('/auditinspection/reject','AuditInspectionController@reject')->name('auditinspection.reject');

Route::post('/auditinspection/addcomment','AuditInspectionController@addcomment')->name('auditinspection.addcomment');

Route::post('/auditinspection/check','AuditInspectionController@check')->name('auditinspection.check');

Route::get('/auditinspection/escalationfield','AuditInspectionController@escalationfield')->name('auditinspection.escalationfield');

Route::get('/auditinspection/getuser','AuditInspectionController@getuser')->name('auditinspection.getuser');

Route::post('/auditinspection/savepv','AuditInspectionController@savepv')->name('auditinspection.savepv');

Route::get('/auditinspection/uploadauditvideo/{id}','AuditInspectionController@uploadauditvideo')->name('auditinspection.uploadauditvideo');

Route::post('/auditinspection/saveauditvideo','AuditInspectionController@saveauditvideo')->name('auditinspection.saveauditvideo');

Route::get('/auditinspection/editauditvideo/{id}','AuditInspectionController@editauditvideo')->name('auditinspection.editauditvideo');

Route::put('/auditinspection/updateauditvideo/{id}','AuditInspectionController@updateauditvideo')->name('auditinspection.updateauditvideo');

Route::post('/auditinspection/clusterheads','AuditInspectionController@clusterheads')->name('auditinspection.clusterheads');


//Routes for reports
Route::group(['middleware' => ['auth'], 'prefix' => 'reports', 'as' => 'reports.'], function () {

    Route::get('plannedwarehouses', ['uses'=>'Admin\ReportController@plannedwarehouses','as' => 'plannedwarehouses']);

    Route::get('auditedwarehouses', ['uses'=>'Admin\ReportController@auditedwarehouses','as' => 'auditedwarehouses']);

    Route::get('clientwiseplannedwarehouses', ['uses'=>'Admin\ReportController@clientwiseplannedwarehouses','as' => 'clientwiseplannedwarehouses']);

    Route::get('auditfindings', ['uses'=>'Admin\ReportController@auditfindings','as' => 'auditfindings']);

    Route::get('clientwisedetail', ['uses'=>'Admin\ReportController@clientwisedetail','as' => 'clientwisedetail']);

    Route::get('auditfindingsdetail', ['uses'=>'Admin\ReportController@auditfindingsdetail','as' => 'auditfindingsdetail']);

    Route::get('auditfindingsdishonoured', ['uses'=>'Admin\ReportController@auditfindingsdishonoured','as' => 'auditfindingsdishonoured']);

    Route::get('auditfindingsdetaildishonoured', ['uses'=>'Admin\ReportController@auditfindingsdetaildishonoured','as' => 'auditfindingsdetaildishonoured']);

    Route::get('warehousewisemismatchreport', ['uses'=>'Admin\ReportController@warehousewisemismatchreport','as' => 'warehousewisemismatchreport']);

    Route::get('warehousewisemismatchreportdetail', ['uses'=>'Admin\ReportController@warehousewisemismatchreportdetail','as' => 'warehousewisemismatchreportdetail']);    
    
});

Route::get('/reminder/sendescalations','ReminderController@sendescalations')->name('auditinspection.sendescalations');


//use App\User;
Route::get("/test",function(){
	//echo "test";
	//echo route('auth.login');
	//echo url('login');
	 //abort(401);
	echo "<pre>";
	print_r(App\User::all()->toArray());
	//print_r(App\User::all()->pluck('name','name'));
	//dd(App\User::all());
})->middleware('Logger');

Route::get("/upload",function(){

    return view('upload');

})->name('upload');

Route::post("/save",function(){
    //dd(request()->file('image'));
    // $result = request()->file('image')->store(
    //     'aryapro',
    //     's3'
    // );
    $file = request()->file('image');
    //print_r($file);die;
    $imageName = 'aryapro/'.$file->getClientOriginalName();

    Storage::disk('s3')->put($imageName, file_get_contents($file));
    Storage::disk('s3')->setVisibility($imageName, 'public');

    $url = Storage::disk('s3')->url($imageName);
    //print_r($url);die;
    return back();
})->name('save');

Route::get('send','MailController@send');

Route::get("/internetnotify",function(){

    return view('internetnotify');

})->name('internetnotify');

Route::get('updateusingcsv','ImportExcelController@updateusingcsv');

resources/views/admin/reports/auditedwarehouses.blade.php
<?php 
    $role = Auth::user()->roles->pluck('name')->first();
?>
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')


@section('content')
    <h3 class="page-title">Current Month's Audited Warehouses</h3>
    
    <div class="clearfix"></div>
    <label></label>
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif

    
    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_list')
        </div>
        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($auditinspections) > 0 ? 'datatable' : '' }} dt-select">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Warehouse Code</th>
                        <th>State</th>
                        <th>Name of Warehouse</th>
                        <th>Location</th>
                        <th>Created Date</th>
                        <th>Type of Warehouse</th>
                        <th>Auditor Name</th>

                    </tr>
                </thead>
                
                <tbody>
                    @if (count($auditinspections) > 0)
                        @foreach ($auditinspections as $ai)
                            <tr data-entry-id="{{ $ai->id }}">
                                <td>{{ $ai->id }}</td>
                                <td>{{ $ai->warehouse_code }}</td>
                                <td>{{ $ai->state }}</td>
                                <td>{{ $ai->name_of_warehouse }}</td>
                                <td>{{ $ai->location_name }}</td>
                                <td>{{ date("d-m-Y",strtotime($ai->created_at)) }}</td>
                                <td>{{ $ai->type_of_warehouse }}</td>
                                <td>{{ $ai->auditor_name }}</td>
                                

                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="9">@lang('global.app_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>


        
    </div>
@stop

@section('javascript') 
<script type="text/javascript">
    

</script>
    
@endsection

resources/views/admin/reports/auditfindings.blade.php
<?php
    $role = Auth::user()->roles->pluck('name')->first();
?>
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')


@section('content')
    <h3 class="page-title">Audit Findings</h3>
    
    <div class="clearfix"></div>
    <label></label>
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif

    <form method="GET" action="{{ route('reports.auditfindings') }}" id="searchForm">
    <div class="col-md-12 row">
        <div class="col-md-3 form-group">
            <label for="from_date" class="control-label">From Date*</label>
            <input class="form-control searchDate" placeholder="" name="from_date" type="text" value="{{ old('from_date', $from_date) }}">
        </div>

        <div class="col-md-3 form-group">
            <label for="to_date" class="control-label">To Date*</label>
            <input class="form-control searchDate" placeholder="" name="to_date" type="text" value="{{ old('to_date', $to_date) }}">
        </div>

        @role('administrator')
        <div class="col-md-3 form-group">
            <label for="name_of_checker" class="control-label">Checker*</label>
            <select class="form-control select2" id="name_of_checker" name="name_of_checker" tabindex="-1" aria-hidden="true">
                <option value="">Select</option>
                @foreach ($checkers as $c)                      
                    <option value="{{$c->name}}" @if (old('name_of_checker') == $c->name) {{ 'selected' }} @endif>{{$c->name}}</option>
                @endforeach
            </select>
        </div>
        @endrole

        <div class="col-md-3 form-group">
            <br>
            <button type="submit" class="btn btn-info">Search</button>
        </div>

        
    </div>
    <div class="clearfix"></div>
    </form>
    <?php
        if(!isset($checker)){
            $checker="";
        }
    ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_list')
        </div>
        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($finalArr) > 0 ? 'datatable' : '' }} dt-select">
                <thead>
                    <tr>
                        <th>S.No.</th>
                        <th>Nature of Audit Observation</th>
                        <th>CM</th>
                        <th>PWH</th>
                        <th>PWH-CM</th>
                        <th>Total</th>
                        
                    </tr>
                </thead>
                
                <tbody>
                    @if (count($finalArr) > 0)
                        @foreach ($finalArr as $key=>$fa)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $fa['particular'] }}</td>
                                <td>
                                    @if($fa['CM']==0)
                                    {{$fa['CM']}} 
                                    @else
                                    <a href="{{route('reports.auditfindingsdetail')}}?field={{$key}}&type=CM&fdate={{$from_date}}&tdate={{$to_date}}&name_of_checker={{$checker}}" class="btn btn-info">{{$fa['CM']}}</a>
                                    @endif
                                </td>
                                <td>@if($fa['PWH']==0)
                                    {{$fa['PWH']}} 
                                    @else
                                    <a href="{{route('reports.auditfindingsdetail')}}?field={{$key}}&type=PWH&fdate={{$from_date}}&tdate={{$to_date}}&name_of_checker={{$checker}}" class="btn btn-info">{{$fa['PWH']}}</a>
                                    @endif</td>
                                <td>@if($fa['PWH-CM']==0)
                                    {{$fa['PWH-CM']}} 
                                    @else
                                    <a href="{{route('reports.auditfindingsdetail')}}?field={{$key}}&type=PWH-CM&fdate={{$from_date}}&tdate={{$to_date}}&name_of_checker={{$checker}}" class="btn btn-info">{{$fa['PWH-CM']}}</a>
                                    @endif</td>
                                <td>{{ $fa['total'] }}</td>
                            
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="8">@lang('global.app_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>


        
    </div>
@stop

@section('javascript') 
<script type="text/javascript">
     //to initialize datepicker plugin  
      $('.searchDate').datepicker({
        autoclose: true,
        format:"dd-mm-yyyy"
      });

    @if(isset($checker))
    $('#name_of_checker').val("{{$checker}}").trigger('change');
    @endif
</script>
    
@endsection

resources/views/admin/reports/auditfindingsdishonoured.blade.php
<?php 
    $role = Auth::user()->roles->pluck('name')->first();
?>
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')


@section('content')
    <h3 class="page-title">Audit Findings</h3>
    
    <div class="clearfix"></div>
    <label></label>
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif

    <form method="GET" action="{{ route('reports.auditfindingsdishonoured') }}" id="searchForm">
    <div class="col-md-12 row">
        <div class="col-md-5 form-group">
            <label for="from_date" class="control-label">From Date*</label>
            <input class="form-control searchDate" placeholder="" name="from_date" type="text" value="{{ old('from_date', $from_date) }}">
        </div>

        <div class="col-md-5 form-group">
            <label for="to_date" class="control-label">To Date*</label>
            <input class="form-control searchDate" placeholder="" name="to_date" type="text" value="{{ old('to_date', $to_date) }}">
        </div>

        <div class="col-md-2 form-group">
            <br>
            <button type="submit" class="btn btn-info">Search</button>
        </div>

        
    </div>
    <div class="clearfix"></div>
    </form>
    
    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_list')
        </div>
        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($finalArr) > 0 ? 'datatable' : '' }} dt-select">
                <thead>
                    <tr>
                        <th>S.No.</th>
                        <th>Nature of Audit Observation</th>
                        <th>CM</th>
                        <th>PWH</th>
                        <th>PWH-CM</th>
                        <th>Total</th>
                        
                    </tr>
                </thead>
                
                <tbody>
                    @if (count($finalArr) > 0)
                        @foreach ($finalArr as $key=>$fa)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $fa['particular'] }}</td>
                                <td>
                                    @if($fa['CM']==0)
                                    {{$fa['CM']}} 
                                    @else
                                    <a href="{{route('reports.auditfindingsdetaildishonoured')}}?field={{$key}}&type=CM&fdate={{$from_date}}&tdate={{$to_date}}" class="btn btn-info">{{$fa['CM']}}</a>
                                    @endif
                                </td>
                                <td>@if($fa['PWH']==0)
                                    {{$fa['PWH']}} 
                                    @else
                                    <a href="{{route('reports.auditfindingsdetaildishonoured')}}?field={{$key}}&type=PWH&fdate={{$from_date}}&tdate={{$to_date}}" class="btn btn-info">{{$fa['PWH']}}</a>
                                    @endif</td>
                                <td>@if($fa['PWH-CM']==0)
                                    {{$fa['PWH-CM']}} 
                                    @else
                                    <a href="{{route('reports.auditfindingsdetaildishonoured')}}?field={{$key}}&type=PWH-CM&fdate={{$from_date}}&tdate={{$to_date}}" class="btn btn-info">{{$fa['PWH-CM']}}</a>
                                    @endif</td>
                                <td>{{ $fa['total'] }}</td>
                            
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="8">@lang('global.app_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>


        
    </div>
@stop

@section('javascript') 
<script type="text/javascript">
     //to initialize datepicker plugin  
      $('.searchDate').datepicker({
        autoclose: true,
        format:"dd-mm-yyyy"
      });
</script>
    
@endsection

resources/views/admin/reports/clientwiseplannedwarehouses.blade.php
<?php 
    $role = Auth::user()->roles->pluck('name')->first();
?>
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')


@section('content')
    <h3 class="page-title">Clientwise Planned Warehouses</h3>
    
    <div class="clearfix"></div>
    <label></label>
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif

    <form method="GET" action="{{ route('reports.clientwiseplannedwarehouses') }}" id="searchForm">
    <div class="col-md-12 row">
        <div class="col-md-3 form-group">
            <label for="from_date" class="control-label">From Date*</label>
            <input class="form-control searchDate" placeholder="" name="from_date" type="text" value="{{ old('from_date', $from_date) }}">
        </div>

        <div class="col-md-3 form-group">
            <label for="to_date" class="control-label">To Date*</label>
            <input class="form-control searchDate" placeholder="" name="to_date" type="text" value="{{ old('to_date', $to_date) }}">
        </div>
        @role('administrator')
        <div class="col-md-3 form-group">
            <label for="name_of_checker" class="control-label">Checker*</label>
            <select class="form-control select2" id="name_of_checker" name="name_of_checker" tabindex="-1" aria-hidden="true">
                <option value="">Select</option>
                @foreach ($checkers as $c)                      
                    <option value="{{$c->name}}" @if (old('name_of_checker') == $c->name) {{ 'selected' }} @endif>{{$c->name}}</option>
                @endforeach
            </select>
        </div>
        @endrole
        <div class="col-md-3 form-group">
            <br>
            <button type="submit" class="btn btn-info">Search</button>
        </div>

        
    </div>
    <div class="clearfix"></div>
    </form>
    <?php
        if(!isset($checker)){
            $checker="";
        }
    ?>   
    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_list')
        </div>
        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($finalArr) > 0 ? 'datatable' : '' }} dt-select">
                <thead>
                    <tr>
                        <th>S.No.</th>
                        <th>Particulars</th>
                        <th>CM</th>
                        <th>PWH</th>
                        <th>PWH-CM</th>
                        <th>Total</th>
                        
                    </tr>
                </thead>
                
                <tbody>
                    @if (count($finalArr) > 0)
                        @foreach ($finalArr as $key=>$fa)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $fa['particular'] }}</td>
                                <td>
                                    @if($fa['CM']==0)
                                    {{$fa['CM']}} 
                                    @else
                                    <a href="{{route('reports.clientwisedetail')}}?field={{$key}}&type=CM&fdate={{$from_date}}&tdate={{$to_date}}&name_of_checker={{$checker}}" class="btn btn-info">{{$fa['CM']}}</a>
                                    @endif
                                </td>
                                <td>@if($fa['PWH']==0)
                                    {{$fa['PWH']}} 
                                    @else
                                    <a href="{{route('reports.clientwisedetail')}}?field={{$key}}&type=PWH&fdate={{$from_date}}&tdate={{$to_date}}&name_of_checker={{$checker}}" class="btn btn-info">{{$fa['PWH']}}</a>
                                    @endif</td>
                                <td>@if($fa['PWH-CM']==0)
                                    {{$fa['PWH-CM']}} 
                                    @else
                                    <a href="{{route('reports.clientwisedetail')}}?field={{$key}}&type=PWH-CM&fdate={{$from_date}}&tdate={{$to_date}}&name_of_checker={{$checker}}" class="btn btn-info">{{$fa['PWH-CM']}}</a>
                                    @endif</td>
                                <td>{{ $fa['total'] }}</td>
                            
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="8">@lang('global.app_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>


        
    </div>
@stop

@section('javascript') 
<script type="text/javascript">
    //to initialize datepicker plugin  
      $('.searchDate').datepicker({
        autoclose: true,
        format:"dd-mm-yyyy"
      });

   @if(isset($checker))
   $('#name_of_checker').val("{{$checker}}").trigger('change');
   @endif 
</script>
    
@endsection

resources/views/admin/reports/warehousewisemismatchreport.blade.php
<?php 
    $role = Auth::user()->roles->pluck('name')->first();
?>
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')


@section('content')
    <h3 class="page-title">Stock Mismatch Report</h3>
    
    <div class="clearfix"></div>
    <label></label>
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif

    <form method="GET" action="{{ route('reports.warehousewisemismatchreport') }}" id="searchForm">
    <div class="col-md-12 row">
        <div class="col-md-5 form-group">
            <label for="from_date" class="control-label">From Date*</label>
            <input class="form-control searchDate" placeholder="" name="from_date" type="text" value="{{ old('from_date', $from_date) }}">
        </div>

        <div class="col-md-5 form-group">
            <label for="to_date" class="control-label">To Date*</label>
            <input class="form-control searchDate" placeholder="" name="to_date" type="text" value="{{ old('to_date', $to_date) }}">
        </div>

        <div class="col-md-2 form-group">
            <br>
            <button type="submit" class="btn btn-info">Search</button>
        </div>

        
    </div>
    <div class="clearfix"></div>
    </form>
    
    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_list')
        </div>
        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($finalArr) > 0 ? 'datatable' : '' }} dt-select">
                <thead>
                    <tr>
                        <th>Audit Id</th>
                        <th>Warehouse Code</th>
                        <th>Name of Warehouse</th>
                        <th>Stock Shartage(Count)</th>
                        <th>Stock Not Tallied(Count)</th>
                        <th>Audit Date</th>
                    </tr>
                </thead>
                
                <tbody>
                    @if (count($finalArr) > 0)
                        @foreach ($finalArr as $key=>$fa)
                            <tr>
                                <td>{{ $fa['id'] }}</td>
                                <td>{{ $fa['warehouse_code'] }}</td>
                                <td>{{ $fa['name_of_warehouse'] }}</td>
                                <td>
                                    @if(isset($fa['shortageCount']))
                                    <a href="{{route('reports.warehousewisemismatchreportdetail')}}?insId={{$fa['id']}}&type=SC&fdate={{$from_date}}&tdate={{$to_date}}" class="btn btn-info">{{$fa['shortageCount']}}</a> 
                                    @else
                                    {{ 0 }}
                                    @endif
                                </td>
                                <td>
                                    @if(isset($fa['notTalliedCount']))
                                    <a href="{{route('reports.warehousewisemismatchreportdetail')}}?insId={{$fa['id']}}&type=NT&fdate={{$from_date}}&tdate={{$to_date}}" class="btn btn-info">{{$fa['notTalliedCount']}}</a> 
                                    @else
                                    {{ 0 }}
                                    @endif
                                </td>
                                <td>{{ date("d-m-Y",strtotime($fa['created_at'])) }}</td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="8">@lang('global.app_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>


        
    </div>
@stop

@section('javascript') 
<script type="text/javascript">
     //to initialize datepicker plugin  
      $('.searchDate').datepicker({
        autoclose: true,
        format:"dd-mm-yyyy"
      });
</script>
    
@endsection